title: Jung-Tsung Li
description: Postdoctoral Researcher <br/> CCAPP, The Ohio State University <br/><br/> E-mail&#58; li.12638<code>&#64;</code>osu.edu
google_analytics: Jung-Tsung Li, UCSD, OSU, CCAPP, physics, astronomy, astrophysics, plasma, dark matter, solar gamma rays
show_downloads: false
avatar: "profile_picture.jpg"
theme: jekyll-theme-minimal
