title: Jung-Tsung Li
#logo: /images/profile.jpg
description: Postdoctoral Researcher <br/> CCAPP, The Ohio State University
#E-mail&#58; li.12638<code>&#64;</code>osu.edu
google_analytics: Jung-Tsung Li, UCSD, OSU, CCAPP, physics, astronomy, astrophysics, plasma, dark matter, solar gamma rays
show_downloads: false
theme: jekyll-theme-minimal
