title: Jung-Tsung Li
#logo: /images/profile.jpg
description: Postdoctoral Researcher <br/> CCAPP, The Ohio State University <br/><br/> E-mail&#58; &#60;li.12638<code>&#64;</code>osu.edu&#62;
google_analytics: Jung-Tsung Li, lijungtsung, UCSD, OSU, CCAPP, physics, astronomy, astrophysics, plasma, dark matter, solar gamma rays
show_downloads: false
theme: jekyll-theme-minimal
url: "https://lijungtsung.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
