title: Jung-Tsung Li | 李融宗

#logo: /images/profile.jpg
description: Research Scientist <br/> CCAPP, The Ohio State University <br/><br/> E-mail&#58; &#60;li.12638<code>&#64;</code>osu.edu&#62;
google_analytics: Jung-Tsung Li, Jungtsung Li, Jung Tsung Li, lijungtsung, UCSD, UC San Diego, OSU, CCAPP, physics, astronomy, astrophysics, plasma, gamma rays, Fermi-LAT, HAWC, solar gamma rays, solar disk, MHD
show_downloads: false
theme: jekyll-theme-minimal
url: "https://lijungtsung.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
